### ISSUE TITLE
Random Error

### ISSUE THREAD

**Issue by khanhtung2012** [RIvance/LaggRemoverRemastered#3]
[??:??:?? ERROR]: Could not pass event AsyncPlayerChatEvent to LaggRemover v0.1-beta
java.lang.UnsupportedOperationException: null
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.handle(CraftScheduler.java:535) ~[folia-1.20.4.jar:g
it-Folia-"ef2c697"]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:235) ~[folia-1.20.4
.jar:git-Folia-"ef2c697"]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:211) ~[folia-1.20.4
.jar:git-Folia-"ef2c697"]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.scheduleSyncRepeatingTask(CraftScheduler.java:206) ~
[folia-1.20.4.jar:git-Folia-"ef2c697"]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.scheduleSyncDelayedTask(CraftScheduler.java:170) ~[f
olia-1.20.4.jar:git-Folia-"ef2c697"]
        at club.ifcserver.laggremover.main.Events.chatDelayCooldown(Events.java:134) ~[LaggRemover-0.1-beta.jar:?]
        at club.ifcserver.laggremover.main.Events.onChat(Events.java:49) ~[LaggRemover-0.1-beta.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor7.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:
git-Folia-"ef2c697"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[folia-api-1.20.4-R0.1-SNAPSHOT.j
ar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[folia-1.20.4.jar:git
-Folia-"ef2c697"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[folia-1.2
0.4.jar:git-Folia-"ef2c697"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[folia-api-1.20.4-R0.1-SNAPSHO
T.jar:?]
        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:416) ~[folia-1.20.4.jar:git-Folia-"ef2c697"]

        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:102) ~[folia-1.20.4.jar:git-Folia-"ef2c69
7"]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2373) ~[?:?]

        at net.minecraft.server.network.ServerGamePacketListenerImpl.broadcastChatMessage(ServerGamePacketListenerImpl.j
ava:2503) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChat$13(ServerGamePacketListenerImpl.j
ava:2221) ~[?:?]
        at net.minecraft.util.FutureChain.lambda$append$1(FutureChain.java:27) ~[folia-1.20.4.jar:git-Folia-"ef2c697"]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:842) ~[?:?]

**Comment by khanhtung2012** [comment]
also I found out that it is related to chatDelay
